export const API_CALL_REQUEST = 'API_CALL_REQUEST';
export const API_CALL_SUCCESS = 'API_CALL_SUCCESS';
export const API_CALL_FAILURE = 'API_CALL_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const QUESTIONS_FETCH_SUCCESS = 'QUESTIONS_FETCH_SUCCESS';
export const QUESTIONS_FETCH_FAILURE = 'QUESTIONS_FETCH_FAILURE';
export const ANSWERS_FETCH_SUCCESS = 'ANSWERS_FETCH_SUCCESS';
export const ANSWERS_FETCH_FAILURE = 'ANSWERS_FETCH_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';
